SUBS-705
EMBL-EBI-SUBS/taxon-validator pull request #14
Opened 2017-08-17 10:37 UTC by rolando-ebi

bumped version of validator common

2017-08-17 14:34 UTC, ke4 requested changes
Missing version change

2017-08-17 14:34 UTC, ke4 commented on build.gradle
> +    compile ("uk.ac.ebi.subs:validator-common:0.1.0-SNAPSHOT") {
Could you change the version, please?
Just increase the PATCH version by 1

2017-08-18 10:35 UTC, fpenim approved these changes

2017-08-21 09:38 UTC, rolando-ebi commented on build.gradle
> +    compile ("uk.ac.ebi.subs:validator-common:0.1.0-SNAPSHOT") {
done

2017-08-21 09:38 UTC, merged